/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author DUC PHU
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    CustomerBUS bus = new CustomerBUS();
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navigation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        customerSection = new javax.swing.JLabel();
        EmployeeSection = new javax.swing.JLabel();
        BranchSection = new javax.swing.JLabel();
        AccountSection = new javax.swing.JLabel();
        CardSection = new javax.swing.JLabel();
        PassbookSection = new javax.swing.JLabel();
        TransactionSection = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Navigation.setBackground(new java.awt.Color(80, 197, 248));
        Navigation.setPreferredSize(new java.awt.Dimension(200, 700));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/admin-icon-50.png"))); // NOI18N
        jLabel1.setText("SGU Bank");

        NavBar.setBackground(new java.awt.Color(80, 197, 248));

        customerSection.setBackground(new java.awt.Color(80, 197, 248));
        customerSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        customerSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-icon-30.png"))); // NOI18N
        customerSection.setText("Khách Hàng");
        customerSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        customerSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerSection.setOpaque(true);
        customerSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerSectionMouseClicked(evt);
            }
        });

        EmployeeSection.setBackground(new java.awt.Color(80, 197, 248));
        EmployeeSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        EmployeeSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee-icon-30.png"))); // NOI18N
        EmployeeSection.setText("Nhân Viên");
        EmployeeSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeSection.setOpaque(true);
        EmployeeSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeSectionMouseClicked(evt);
            }
        });

        BranchSection.setBackground(new java.awt.Color(80, 197, 248));
        BranchSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        BranchSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BranchSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/branch-icon-30.png"))); // NOI18N
        BranchSection.setText("Chi Nhánh");
        BranchSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BranchSection.setOpaque(true);
        BranchSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BranchSectionMouseClicked(evt);
            }
        });

        AccountSection.setBackground(new java.awt.Color(80, 197, 248));
        AccountSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        AccountSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account-icon-30.png"))); // NOI18N
        AccountSection.setText("Tài Khoản");
        AccountSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountSection.setOpaque(true);
        AccountSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountSectionMouseClicked(evt);
            }
        });

        CardSection.setBackground(new java.awt.Color(80, 197, 248));
        CardSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        CardSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/card-icon-30.png"))); // NOI18N
        CardSection.setText("Thẻ");
        CardSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CardSection.setOpaque(true);
        CardSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardSectionMouseClicked(evt);
            }
        });

        PassbookSection.setBackground(new java.awt.Color(80, 197, 248));
        PassbookSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        PassbookSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassbookSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/passbook-icon-30.png"))); // NOI18N
        PassbookSection.setText("Sổ Tiết Kiệm");
        PassbookSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PassbookSection.setOpaque(true);
        PassbookSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassbookSectionMouseClicked(evt);
            }
        });

        TransactionSection.setBackground(new java.awt.Color(80, 197, 248));
        TransactionSection.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TransactionSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TransactionSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaction-icon-30.png"))); // NOI18N
        TransactionSection.setText("Lịch Sử GD");
        TransactionSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransactionSection.setOpaque(true);
        TransactionSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionSectionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerSection, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(EmployeeSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BranchSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AccountSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CardSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PassbookSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TransactionSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(customerSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EmployeeSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BranchSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AccountSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CardSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PassbookSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TransactionSection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        List<JLabel> navButtons = Arrays.asList(customerSection, EmployeeSection, BranchSection, AccountSection, PassbookSection, TransactionSection, CardSection);

        for(JLabel navButton : navButtons)
        {
            navButton.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e)
                {

                    for(JLabel navBtn : navButtons)
                    {

                        navBtn.setBackground(new Color(0x50C5F8));
                    }

                    navButton.setBackground(new Color(0xB0DAFF));
                }

                public void mouseEntered(MouseEvent e)
                {
                    navButton.setText("<html><u>" + navButton.getText() + "</u></html>");
                }

                public void mouseExited(MouseEvent e)
                {
                    navButton.setText(navButton.getText().replaceAll("<html><u>", ""));
                    navButton.setText(navButton.getText().replaceAll("</u></html>", ""));
                }
            });
        }

        javax.swing.GroupLayout NavigationLayout = new javax.swing.GroupLayout(Navigation);
        Navigation.setLayout(NavigationLayout);
        NavigationLayout.setHorizontalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        NavigationLayout.setVerticalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(255, 204, 204));
        MainPanel.setPreferredSize(new java.awt.Dimension(1150, 700));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Chọn chức năng quản lý ở bên phải");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Trang quản lý So Gu Bank");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel2))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel3)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSectionMouseClicked
        
        
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        CustomerPanel cusPanel = new CustomerPanel();
        cusPanel.setPreferredSize(new Dimension(1000, 600));
        MainPanel.setLayout(new GridLayout(1,1));
        MainPanel.add(cusPanel);
        MainPanel.revalidate();
        MainPanel.repaint();
        
    }//GEN-LAST:event_customerSectionMouseClicked

    private void EmployeeSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeSectionMouseClicked
        EmployeeGUI empGUI = new EmployeeGUI();
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        MainPanel.setLayout(new GridLayout(1,1));
        MainPanel.add(empGUI);
    }//GEN-LAST:event_EmployeeSectionMouseClicked

    private void BranchSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BranchSectionMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        BranchGUI braPanel = new BranchGUI();
        MainPanel.setLayout(new GridLayout(1,1));
        MainPanel.add(braPanel);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_BranchSectionMouseClicked

    private void AccountSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountSectionMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        AccountPanel accPanel = new AccountPanel();
        MainPanel.setLayout(new GridLayout(1,1));
        MainPanel.add(accPanel);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_AccountSectionMouseClicked

    private void CardSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardSectionMouseClicked
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        MainPanel.setLayout(new GridLayout(1, 1));
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_CardSectionMouseClicked

    private void PassbookSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassbookSectionMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        PassBookPanel bookPanel = new PassBookPanel();
        MainPanel.setLayout(new GridLayout(1, 1));
        MainPanel.add(bookPanel);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_PassbookSectionMouseClicked

    private void TransactionSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionSectionMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.revalidate();
        MainPanel.repaint();
        TransactionPanel transPanel = new TransactionPanel();
        MainPanel.setLayout(new GridLayout(1, 1));
        MainPanel.add(transPanel);
    }//GEN-LAST:event_TransactionSectionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set Windows look and feel
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountSection;
    private javax.swing.JLabel BranchSection;
    private javax.swing.JLabel CardSection;
    private javax.swing.JLabel EmployeeSection;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel Navigation;
    private javax.swing.JLabel PassbookSection;
    private javax.swing.JLabel TransactionSection;
    private javax.swing.JLabel customerSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
