/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class BranchInfo extends javax.swing.JFrame {

    BranchBUS bus = new BranchBUS();

    public BranchInfo(String ID) {
        initComponents();
        lBranchIDInfor.setText(ID);
    }
    
    public BranchInfo(BranchDTO braTemp) {
        initComponents();
        setValue(braTemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lMain = new javax.swing.JLabel();
        lBranchID = new javax.swing.JLabel();
        lBranchAddress = new javax.swing.JLabel();
        lBranchManager = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        lBranchIDInfor = new javax.swing.JLabel();
        txtBranchAddress = new javax.swing.JTextField();
        txtBranchManager = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lMain.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lMain.setForeground(new java.awt.Color(0, 0, 0));
        lMain.setText("BẢNG THÔNG TIN CHI NHÁNH");

        lBranchID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lBranchID.setForeground(new java.awt.Color(0, 0, 0));
        lBranchID.setText("MÃ CHI NHÁNH:");

        lBranchAddress.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lBranchAddress.setForeground(new java.awt.Color(0, 0, 0));
        lBranchAddress.setText("ĐỊA CHỈ CHI NHÁNH:");

        lBranchManager.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lBranchManager.setForeground(new java.awt.Color(0, 0, 0));
        lBranchManager.setText("TÊN QUẢN LÝ:");

        bSave.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        bSave.setForeground(new java.awt.Color(0, 0, 0));
        bSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/save24.png"))); // NOI18N
        bSave.setText("LƯU");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bDel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        bDel.setForeground(new java.awt.Color(0, 0, 0));
        bDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/del24.png"))); // NOI18N
        bDel.setText("XÓA");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });

        lBranchIDInfor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lBranchIDInfor.setForeground(new java.awt.Color(0, 0, 0));
        lBranchIDInfor.setText("IDIDIDIDID");

        txtBranchAddress.setBackground(new java.awt.Color(0, 0, 0));
        txtBranchAddress.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtBranchAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtBranchAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBranchAddressKeyPressed(evt);
            }
        });

        txtBranchManager.setBackground(new java.awt.Color(0, 0, 0));
        txtBranchManager.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtBranchManager.setForeground(new java.awt.Color(255, 255, 255));
        txtBranchManager.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBranchManagerKeyPressed(evt);
            }
        });

        bAdd.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        bAdd.setForeground(new java.awt.Color(0, 0, 0));
        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/add24.png"))); // NOI18N
        bAdd.setText("THÊM");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMain)
                .addGap(323, 323, 323))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lBranchAddress)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lBranchID)
                            .addComponent(bAdd)
                            .addComponent(lBranchManager))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lBranchIDInfor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBranchAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bDel)))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lMain)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBranchID)
                    .addComponent(lBranchIDInfor))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBranchAddress)
                    .addComponent(txtBranchAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBranchManager)
                    .addComponent(txtBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa hết thông tin?");
        if(choice == JOptionPane.YES_OPTION){
            txtBranchAddress.setText("");
            txtBranchManager.setText("");
        }
    }//GEN-LAST:event_bDelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn muốn lưu thông tin đã sửa?");
        if(choice == JOptionPane.YES_OPTION && bus.isUnique(lBranchIDInfor.getText())==false){
            BranchDTO braTemp = new BranchDTO();
            braTemp.setBranchAddress(bus.normalization(txtBranchAddress.getText()));
            braTemp.setBranchName(bus.generateBranchName(braTemp));
            braTemp.setBranchManager(bus.normalization(txtBranchManager.getText()));
            JOptionPane.showMessageDialog(null, "Lưu thành công");
            this.dispose();
            bus.edit(braTemp, lBranchIDInfor.getText());
        }else{
            JOptionPane.showMessageDialog(null, "BẠN BẤM NHẦM NÚT LƯU");
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn muốn thêm chi nhánh?");
        if(choice == JOptionPane.YES_OPTION && bus.isUnique(lBranchIDInfor.getText())){
            BranchDTO braTemp = new BranchDTO();
            braTemp.setBranchID(lBranchIDInfor.getText());
            braTemp.setBranchAddress(bus.normalization(txtBranchAddress.getText()));
            braTemp.setBranchName(bus.generateBranchName(braTemp));
            braTemp.setBranchManager(bus.normalization(txtBranchManager.getText()));
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            this.dispose();
            bus.add(braTemp);
        }else{
            JOptionPane.showMessageDialog(null, "BẠN BẤM NHẦM NÚT THÊM");
        }
    }//GEN-LAST:event_bAddActionPerformed

    private void txtBranchAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBranchAddressKeyPressed

    }//GEN-LAST:event_txtBranchAddressKeyPressed

    private void txtBranchManagerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBranchManagerKeyPressed
        if(evt.getKeyChar()>='A' || evt.getKeyChar()>='a' || evt.getKeyChar()>='Z' || evt.getKeyChar()>='z' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode() == evt.VK_SPACE){
            txtBranchManager.setEditable(true);
        }else{
            txtBranchManager.setEditable(false);
        }
    }//GEN-LAST:event_txtBranchManagerKeyPressed

    
    private void setValue(BranchDTO braTemp){
        lBranchIDInfor.setText(braTemp.getBranchID());
        txtBranchAddress.setText(braTemp.getBranchAddress());
        txtBranchManager.setText(braTemp.getBranchManager());
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBranchAddress;
    private javax.swing.JLabel lBranchID;
    private javax.swing.JLabel lBranchIDInfor;
    private javax.swing.JLabel lBranchManager;
    private javax.swing.JLabel lMain;
    private javax.swing.JTextField txtBranchAddress;
    private javax.swing.JTextField txtBranchManager;
    // End of variables declaration//GEN-END:variables
}
