/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author DUC PHU
 */
public class PassBookCreate extends javax.swing.JFrame {

    /**
     * Creates new form PassBookCreate
     */
    private CustomerDTO customer;
    private PaymentAccountBUS accBus = new PaymentAccountBUS();
    private BranchBUS braBus = new BranchBUS();
    private PassBookTypeBUS bookTypeBus = new PassBookTypeBUS();
    private PassBookBUS bookBus = new PassBookBUS();
    private long inAmount;
    private float interest;
    private long outAmount;
    private long accBalance;
    private String bookTypeID;
    private int period;
    Validator doValid = new Validator();
    public PassBookCreate(CustomerDTO customer) {
        this.customer = customer;
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbAccList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbbMonthPeriodList = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfInterestRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfOutAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbbBranchList = new javax.swing.JComboBox<>();
        btnConfirm = new javax.swing.JButton();
        lbAccBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tạo 1 Sổ Tiết Kiệm Mới");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Chọn Tài Khoản lấy tiền : ");

        cbbAccList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbAccList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAccListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nhập số Tiền : ");

        tfAmount.setEditable(false);
        tfAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-icon-10.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/minus-icon-10.png"))); // NOI18N
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("0");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Chọn Kỳ Hạn : ");

        cbbMonthPeriodList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonthPeriodListActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("% Lãi Xuất : ");

        tfInterestRate.setEditable(false);
        tfInterestRate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tiền Lãi : ");

        tfOutAmount.setEditable(false);
        tfOutAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Chi Nhánh phụ trách : ");

        btnConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfirm.setText("Xác Nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lbAccBalance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbAccBalance.setText("Số Dư : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(469, 469, 469))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAccBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbAccList, 0, 205, Short.MAX_VALUE)
                        .addComponent(tfAmount))
                    .addComponent(tfOutAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMonthPeriodList, 0, 188, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInterestRate)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbBranchList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbAccList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMonthPeriodList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAccBalance)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOutAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbBranchList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(88, 88, 88))
        );

        loadAccList();
        loadPeriod();
        loadBranchList();
        lbAccBalance.setText("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void loadAccList()
    {
        ArrayList<PaymentAccountDTO> accList = new ArrayList<>();
        ArrayList<PaymentAccountDTO> searchResult = accBus.searchByOwnerID(customer.getCustomerID());
        accList.addAll(searchResult);
        for(PaymentAccountDTO account : accList)
        {
            cbbAccList.addItem(account.getAccountNumber());
        }
    }
    
    void loadBranchList()
    {
        for(BranchDTO bra : braBus.braAL)
        {
            cbbBranchList.addItem(bra.getBranchName());
        }
    }
    
    void loadPeriod()
    {
        for(PassBookTypeDTO type : bookTypeBus.typeList)
        {
            cbbMonthPeriodList.addItem(type.getMonthPeriod());
        }
    }
    
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        PaymentAccountDTO account = new PaymentAccountDTO();
        account = accBus.getAccByNum(cbbAccList.getSelectedItem().toString());
        if(tfOutAmount.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin");
        }
        else if(inAmount > account.getAccountBalance())
        {
            JOptionPane.showMessageDialog(this, "Số tiền ko đủ");
        }
        else{
            String bookTypeID = bookTypeBus.outputIDByMonth(cbbMonthPeriodList.getSelectedItem().toString());
            String cusID = customer.getCustomerID();
            String braID = braBus.outputIDByName(cbbBranchList.getSelectedItem().toString());
            LocalDate createdDate = LocalDate.now();
            LocalDate depositDate = createdDate.plusDays(period);
            PassBookDTO book = new PassBookDTO();
            book.setBookType(bookTypeID);
            book.setID(bookBus.generateID());
            book.setCustomerID(cusID);
            book.setInterestAmount(inAmount);
            book.setDepositAmount(outAmount);
            book.setCreatedDate(createdDate);
            book.setDepositDate(depositDate);
            book.setChangeDate(depositDate);
            book.setStatus("Trong kỳ hạn");
            book.setBranchID(braID);
            book.setMonth(cbbMonthPeriodList.getSelectedItem().toString());
            book.setInterest(interest);
            bookBus.add(book);
            account.setAccountBalance(account.getAccountBalance() - inAmount);
            accBus.edit(account.getAccountID(), account);
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cbbAccListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAccListActionPerformed
        // TODO add your handling code here:
        PaymentAccountDTO account = new PaymentAccountDTO();
        account = accBus.getAccByNum(cbbAccList.getSelectedItem().toString());
        lbAccBalance.setText("Số dư : " +doValid.formatMoney(account.getAccountBalance()));
    }//GEN-LAST:event_cbbAccListActionPerformed

    private void cbbMonthPeriodListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonthPeriodListActionPerformed
        // TODO add your handling code here:
        interest = bookTypeBus.outputRateByMonth(cbbMonthPeriodList.getSelectedItem().toString());
        tfInterestRate.setText(interest+"");
        period = bookTypeBus.outputPeriodByMonth(cbbMonthPeriodList.getSelectedItem().toString());
        outAmount = (inAmount * Math.round(interest * period))/365 + inAmount;
        tfOutAmount.setText(doValid.formatMoney(outAmount));
    }//GEN-LAST:event_cbbMonthPeriodListActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        long number = Long.parseLong(JOptionPane.showInputDialog("Nhập số tiền: "));
        if(number > 0)
        {
            inAmount += number;
            tfAmount.setText("" +doValid.formatMoney(inAmount));
            period = bookTypeBus.outputPeriodByMonth(cbbMonthPeriodList.getSelectedItem().toString());
            outAmount = (inAmount * Math.round(interest * period))/365 + inAmount;
            tfOutAmount.setText(doValid.formatMoney(outAmount));
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        if (inAmount == 0) {
            JOptionPane.showMessageDialog(this, "Số Tiền Đã là 0!");
        }
        else{
            long number = Long.parseLong(JOptionPane.showInputDialog("Nhập số tiền: "));
            if(number > inAmount || number < 0)
            {
                JOptionPane.showMessageDialog(this, "Số Tiền trừ không hợp lệ!");
            }
            else{
                inAmount -= number;
                tfAmount.setText("" +doValid.formatMoney(inAmount));
                period = bookTypeBus.outputPeriodByMonth(cbbMonthPeriodList.getSelectedItem().toString());
                outAmount = (inAmount * Math.round(interest * period))/365 + inAmount;
                tfOutAmount.setText(doValid.formatMoney(outAmount));
            }
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PassBookCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PassBookCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PassBookCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PassBookCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PassBookCreate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbbAccList;
    private javax.swing.JComboBox<String> cbbBranchList;
    private javax.swing.JComboBox<String> cbbMonthPeriodList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbAccBalance;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfInterestRate;
    private javax.swing.JTextField tfOutAmount;
    // End of variables declaration//GEN-END:variables
}
