/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author DUC PHU
 */
public class PassBookUserForm extends javax.swing.JPanel {

    /**
     * Creates new form PassBookUserForm
     */
    private PassBookDTO book;
    private CustomerDTO customer;
    private Validator doValid = new Validator();
    public PassBookUserForm(PassBookDTO book, CustomerDTO customer) {
        this.book = book;
        this.customer = customer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInAmount = new javax.swing.JLabel();
        lbMonthPeriod = new javax.swing.JLabel();
        lbInterestRate = new javax.swing.JLabel();
        lbOutAmount = new javax.swing.JLabel();
        lbCreatedDate = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbInAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbInAmount.setText("999.999.999.999");

        lbMonthPeriod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbMonthPeriod.setText("24 tháng");

        lbInterestRate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbInterestRate.setText("9.99");

        lbOutAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbOutAmount.setText("999.999.999.999");

        lbCreatedDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCreatedDate.setText("dd/mm/yyyyy");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon-20.png"))); // NOI18N
        btnEdit.setText("Chi Tiết");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lbMonthPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lbOutAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lbCreatedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbInAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(lbMonthPeriod)
                .addComponent(lbInterestRate)
                .addComponent(lbOutAmount)
                .addComponent(lbCreatedDate)
                .addComponent(btnEdit))
        );

        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        lbInAmount.setText(doValid.formatMoney(book.getInterestAmount()));
        lbMonthPeriod.setText(book.getMonth());
        lbInterestRate.setText(book.getInterest()+ "");
        lbOutAmount.setText(doValid.formatMoney(book.getDepositAmount()));
        lbCreatedDate.setText(doValid.toUIDate(book.getCreatedDate()));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        PassBookUserInfo bookInfo = new PassBookUserInfo(book, customer);
        bookInfo.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lbCreatedDate;
    private javax.swing.JLabel lbInAmount;
    private javax.swing.JLabel lbInterestRate;
    private javax.swing.JLabel lbMonthPeriod;
    private javax.swing.JLabel lbOutAmount;
    // End of variables declaration//GEN-END:variables
}
