/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author DUC PHU
 */
public class SmallUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountForm
     */
    
    private String customerID;
    
    public SmallUserPanel(CustomerDTO customer) {
        initComponents(customer);
        this.customerID = customer.getCustomerID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(CustomerDTO customer) {

        lbID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(316, 60));

        lbID.setBackground(new java.awt.Color(204, 255, 255));
        lbID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbID.setText("00000000");
        lbID.setOpaque(true);

        lbName.setBackground(new java.awt.Color(204, 255, 255));
        lbName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbName.setText("Test Test Testtt Test Test");
        lbName.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        lbID.setText("" +customer.getCustomerID());
        lbName.setText("" +customer.getCusFullName());
        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

    }// </editor-fold>//GEN-END:initComponents

    public String getCustomerID()
    {
        return this.customerID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
