/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author DUC PHU
 */
public class TransactionForm extends javax.swing.JPanel {

    /**
     * Creates new form TransactionForm
     */
    TransactionHistoryDTO history;
    Validator doValid = new Validator();
    public TransactionForm(TransactionHistoryDTO history) {
        this.history = history;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSenderName = new javax.swing.JLabel();
        lbReceiverName = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbSenderName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbSenderName.setText("Test Test Test Test");

        lbReceiverName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbReceiverName.setText("Test Test Test Test");

        lbAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbAmount.setText("999.999.999.999");

        lbDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDate.setText("dd/mm/yyyy");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon-20.png"))); // NOI18N
        btnEdit.setText("Chi Tiết");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSenderName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbReceiverName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(lbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnEdit)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbSenderName, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(lbReceiverName)
                .addComponent(lbAmount)
                .addComponent(lbDate)
                .addComponent(btnEdit))
        );

        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        lbSenderName.setText(history.getSenderName());
        lbReceiverName.setText(history.getReceiverName());
        lbAmount.setText(doValid.formatMoney(history.getTransAmount()));
        lbDate.setText(doValid.toUIDate(history.getTransDate()));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        TransInfo transInfo = new TransInfo(history);
        transInfo.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbReceiverName;
    private javax.swing.JLabel lbSenderName;
    // End of variables declaration//GEN-END:variables
}
