/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author DUC PHU
 */
public class TransactionManage extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPanel
     */
    private long amount = 0;
    private JPanel mainpanel;
    private CustomerDTO customer;
    private Validator doValid = new Validator();
    private PaymentAccountBUS accBus = new PaymentAccountBUS();
    public TransactionManage(JPanel mainpanel, CustomerDTO customer) {
        this.mainpanel = mainpanel;
        this.customer = customer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tfContent = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbAccList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTarNumber = new javax.swing.JTextField();
        tfTarName = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfFee = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tarNumWarn = new javax.swing.JLabel();
        lbAccountBalance = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));

        tfContent.setColumns(15);
        tfContent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfContent.setRows(4);
        jScrollPane2.setViewportView(tfContent);
        tfContent.setWrapStyleWord(true);
        tfContent.setLineWrap(true);
        tfContent.setText("" +customer.getCusFullName()+ " chuyển tiền");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thực Hiện Giao Dịch chuyển tiền");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nội Dung");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Chọn Tài Khoản GD");

        cbbAccList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbAccList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAccListActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Số Tiền");

        tfAmount.setEditable(false);
        tfAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfAmountPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Số TK Người Thụ Hưởng");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Tên Người Thụ Hưởng");

        tfTarNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfTarNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTarNumberFocusLost(evt);
            }
        });
        tfTarNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTarNumberKeyPressed(evt);
            }
        });

        tfTarName.setEditable(false);
        tfTarName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfirm.setText("Xác Nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Lệ Phí (1%)");

        tfFee.setEditable(false);
        tfFee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-icon-10.png"))); // NOI18N
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/minus-icon-10.png"))); // NOI18N
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReset.setText("0");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tarNumWarn.setForeground(new java.awt.Color(255, 51, 51));
        tarNumWarn.setText("Số Tài Khoản không hợp lệ hoặc không tồn tại");

        lbAccountBalance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbAccountBalance.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(tfAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(cbbAccList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(tfFee, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(lbAccountBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarNumWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(tfTarNumber)
                            .addComponent(tfTarName)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(btnConfirm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbAccList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tarNumWarn)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbAccountBalance)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        loadAccList();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTarNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTarNumberFocusLost
        // TODO add your handling code here:
        if(doValid.isExistAccNumber(tfTarNumber.getText()) == false)
        {
            
            tarNumWarn.setText("Số Tài Khoản không hợp lệ hoặc không tồn tại");
        }
        else if(tfTarNumber.getText().equals(cbbAccList.getSelectedItem().toString()))
        {
            tarNumWarn.setText("Số Tài Khoản bị trùng, hãy chọn số khác");
        }
        else
        {
            CustomerDTO customer = new CustomerDTO();
            accBus.getOwnerByNumber(tfTarNumber.getText()).getCusFullName();
            System.out.println("" +accBus.getOwnerByNumber(tfTarNumber.getText()).getCusFullName());
            tfTarName.setText("" +accBus.getOwnerByNumber(tfTarNumber.getText()).getCusFullName());
            tarNumWarn.setText("");
        }
    }//GEN-LAST:event_tfTarNumberFocusLost

    private void tfTarNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTarNumberKeyPressed
        // TODO add your handling code here:
        tarNumWarn.setText("");
    }//GEN-LAST:event_tfTarNumberKeyPressed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
//        mainpanel.removeAll();
//        mainpanel.revalidate();
//        mainpanel.repaint();
//        TransactionResult transPanel = new TransactionResult(mainpanel, customer);
//        mainpanel.setLayout(new GridLayout(1, 1));
//        mainpanel.add(transPanel);
        
        long transAmount = amount;
        long accBalance = accBus.getBalanceByNumber(cbbAccList.getSelectedItem().toString());
        float a = 0.01f;
        PaymentAccountDTO senderAcc = accBus.getAccByNum(cbbAccList.getSelectedItem().toString());
        long fee = Math.round(amount * a);
        if(doValid.isExistAccNumber(tfTarNumber.getText()) == false
                || tfTarNumber.getText().equals(cbbAccList.getSelectedItem().toString()))
        {
            JOptionPane.showMessageDialog(null, "Số Tài Khoản Nhập chưa hợp lệ !");
        }
        else if(transAmount + fee > accBalance)
        {
            JOptionPane.showMessageDialog(null, "Tài Khoản không đủ số dư !");
        }
        else if(!senderAcc.getStatus().equals("Đang hoạt động"))
        {
            JOptionPane.showMessageDialog(null, "Tài Khoản bị khóa hoặc vô hiệu hóa !");
        }
        else{
            
            senderAcc = accBus.getAccByNum(cbbAccList.getSelectedItem().toString());
            String senderName = senderAcc.getCustomerName();
            String senderAccNum = cbbAccList.getSelectedItem().toString();
            senderAcc.DecreaseBalance(transAmount + fee);
            
            PaymentAccountDTO receiverAcc = new PaymentAccountDTO();
            receiverAcc = accBus.getAccByNum(tfTarNumber.getText());
            String receiverName = receiverAcc.getCustomerName();
            String receiverAccNum = tfTarNumber.getText();
            receiverAcc.IncreaseBalance(transAmount);
            
            accBus.edit(senderAcc.getAccountID(), senderAcc);
            accBus.edit(receiverAcc.getAccountID(), receiverAcc);
            
            String transContent = tfContent.getText();
            LocalDate transDate = LocalDate.now();
            
            long senderRemain = senderAcc.getAccountBalance();
            long receiverRemain = receiverAcc.getAccountBalance();
            
            TransactionHistoryDTO history = new TransactionHistoryDTO();
            TransactionHistoryBUS hisBus = new TransactionHistoryBUS();
            history.setTransID(hisBus.generateID());
            history.setSenderID(senderAcc.getCustomerID());
            history.setSenderAcc(senderAccNum);
            history.setReceiverID(receiverAcc.getCustomerID());
            history.setReceiverAcc(receiverAccNum);
            history.setSenderRemain(senderRemain);
            history.setReceiverRemain(receiverRemain);
            history.setTransContent(transContent);
            history.setTransAmount(transAmount);
            history.setFee(fee);
            history.setTransDate(transDate);
            hisBus.add(history);
            
            mainpanel.removeAll();
            mainpanel.revalidate();
            mainpanel.repaint();
            TransactionResult transPanel = new TransactionResult(mainpanel, customer, history);
            mainpanel.setLayout(new GridLayout(1, 1));
            mainpanel.add(transPanel);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
//        long amount = 0;
// 
//        JDialog inputDialog = new JDialog();
//        inputDialog.setSize(200, 100);
//        inputDialog.setLayout(new BorderLayout());
//        JLabel label = new JLabel("Nhập số tiền thêm vào:");
//        JTextField tfMoney = new JTextField();
//        JButton okButton = new JButton("OK");
//        okButton.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent e)
//            {
//                try{
//                    long number = Long.parseLong(tfMoney.getText());
//                    amount += number;
//                    inputDialog.dispose();
//                }
//                catch (NumberFormatException ex) {
//                // Nếu giá trị nhập không phải số, hiển thị thông báo lỗi
//                JOptionPane.showMessageDialog(inputDialog, "Vui lòng nhập số nguyên");
//                }
//            }
//        });
//        inputDialog.add(label, BorderLayout.NORTH);
//        inputDialog.add(tfMoney, BorderLayout.CENTER);
//        inputDialog.add(okButton, BorderLayout.SOUTH);
//
//        inputDialog.setVisible(true);

        long number = Long.parseLong(JOptionPane.showInputDialog("Nhập số tiền: "));
        if(number > 0)
        {
            amount += number;
            tfAmount.setText("" +doValid.formatMoney(amount));
            float a = 0.01f;
            long fee = Math.round(amount * a);
            tfFee.setText(doValid.formatMoney(fee));
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        if (amount == 0) {
            JOptionPane.showMessageDialog(this, "Số Tiền Đã là 0!");
        }
        else {
            long number = Long.parseLong(JOptionPane.showInputDialog("Nhập số tiền: "));
            if(number > amount || number < 0)
            {
                JOptionPane.showMessageDialog(this, "Số Tiền trừ không hợp lệ!");
            }
            else{
                amount -= number;
                tfAmount.setText("" +doValid.formatMoney(amount));
                float a = 0.01f;
                long fee = Math.round(amount * a);
                tfFee.setText(doValid.formatMoney(fee));
            }
            
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        amount = 0;
        tfAmount.setText("" +doValid.formatMoney(amount));
    }//GEN-LAST:event_btnResetActionPerformed

    private void tfAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfAmountPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfAmountPropertyChange

    private void cbbAccListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAccListActionPerformed
        // TODO add your handling code here:
        lbAccountBalance.setText("Số dư : "+doValid.formatMoney(accBus.getAccByNum(cbbAccList.getSelectedItem().toString()).getAccountBalance()));
    }//GEN-LAST:event_cbbAccListActionPerformed

    public void loadAccList()
    {
        
        ArrayList<PaymentAccountDTO> accList = new ArrayList<>();
        ArrayList<PaymentAccountDTO> searchResult = accBus.searchByOwnerID(customer.getCustomerID());
        accList.addAll(searchResult);
        for(PaymentAccountDTO account : accList)
        {
            cbbAccList.addItem(account.getAccountNumber());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbbAccList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAccountBalance;
    private javax.swing.JLabel tarNumWarn;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextArea tfContent;
    private javax.swing.JTextField tfFee;
    private javax.swing.JTextField tfTarName;
    private javax.swing.JTextField tfTarNumber;
    // End of variables declaration//GEN-END:variables
}
