/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.event.MouseInputAdapter;

import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author DUC PHU
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public UserPanel(CustomerDTO customer) {
        initComponents(customer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(CustomerDTO customer) {

        lbID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        jbtnEdit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(910, 60));

        lbID.setBackground(new java.awt.Color(204, 255, 255));
        lbID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbID.setText("" +customer.getCustomerID());
        lbID.setOpaque(true);

        lbName.setBackground(new java.awt.Color(204, 255, 255));
        lbName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbName.setText("" +customer.getCusFullName());
        lbName.setOpaque(true);

        lbPhone.setBackground(new java.awt.Color(204, 255, 255));
        lbPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbPhone.setText("" +customer.getPhone());
        lbPhone.setOpaque(true);

        lbMail.setBackground(new java.awt.Color(204, 255, 255));
        lbMail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbMail.setForeground(new java.awt.Color(51, 51, 51));
        lbMail.setText("" +customer.getEmail());
        lbMail.setOpaque(true);

        jbtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon-20.png"))); // NOI18N
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt, customer);
            }
        });

        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-2-icon-20.png"))); // NOI18N
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt, customer);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbMail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnEdit)
                                .addComponent(jbtnDelete)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt, CustomerDTO customer) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        CustomerBUS cusBus = new CustomerBUS();
        PaymentAccountBUS accBus = new PaymentAccountBUS();
        int result = JOptionPane.showConfirmDialog(null, "Xóa khách hàng : "+customer.getCusFullName()+" ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        
        if (result == JOptionPane.YES_OPTION) {
             cusBus.delete(customer.getCustomerID());
             accBus.deleteByCustomer(customer.getCustomerID());
             JOptionPane.showMessageDialog(null, "Xóa khách hàng thành công");
             JOptionPane.getRootFrame().dispose();
        } else {
            // Đóng cửa sổ hiện lên
        }
        
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt, CustomerDTO customer) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
        UserInfo userInfoPopUp = new UserInfo(customer);
        userInfoPopUp.setVisible(true);
        
    }//GEN-LAST:event_jbtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhone;
    // End of variables declaration//GEN-END:variables
}
